steps:
  # Generate version number using date and build number
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$(date +%Y%m%d).$BUILD_ID" > /workspace/version.txt
        VERSION=$(cat /workspace/version.txt)
        echo "Building version: $${VERSION} hahaha"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "-c"
      - |
        docker build -t reactjs-stg/learn-cb:1.0.0 -f Dockerfile.stg .

substitutions:
  _SERVICE_NAME: learn-cb

options:
  logging: CLOUD_LOGGING_ONLY
