steps:
  # Generate version number using date and build number
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$(date +%Y%m%d).$BUILD_ID" > /workspace/version.txt
        VERSION=$(cat /workspace/version.txt)
        echo "Building version: $${VERSION} hahaha"
  
 - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$(cat /workspace/version.txt)',
      '.'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
